### ISSUE TITLE
订单创建后，下发消息失败[设备此时断链]

### ISSUE THREAD

**Issue by yuanl2** [yuanl2/hsbackend#81]
2018-11:24 23:40:47.333 [https-openssl-nio-443-exec-6] [INFO] [c.h.s.controller.WXPayController] - packge sign value:8BD3966D8D5FF93E98C254D8A31DB9F6
2018-11:24 23:40:47.339 [https-openssl-nio-443-exec-6] [INFO] [c.h.s.controller.WXPayController] - create order order{id=4201, orderID=2018112423404722974, deviceID=201808020007, deviceName=null, consumeType=27, startTime=null, endTime=null, duration=910, price=10.0, createTime=2018-11-24T23:40:47.334, orderStatus=0, orderType=1, userID=11}
2018-11:24 23:40:47.654 [Timer-0] [INFO] [c.h.server.service.HeartBeatService] - DeviceConnect disconnect 898604301118C1638006
2018-11:24 23:40:47.661 [Timer-0] [INFO] [com.hansun.server.db.DataStore] - update device before 1 update value device{id=52deviceID=201808020007, type=100, name=null, locationID=20, userID=11, status=0, simCard=898604301118C1638006, port=1, managerStatus=0, consumeType=4, version=01, storeID=1}
2018-11:24 23:40:53.345 [https-openssl-nio-443-exec-10] [INFO] [c.h.s.controller.WXPayController] - wechat pay callback : modify order = 2018112423404722974 status to PAYDONE 
2018-11:24 23:40:53.350 [https-openssl-nio-443-exec-10] [INFO] [com.hansun.server.db.OrderStore] - update order = order{id=4201, orderID=2018112423404722974, deviceID=201808020007, deviceName=null, consumeType=27, startTime=null, endTime=null, duration=910, price=10.0, createTime=2018-11-24T23:40:47, orderStatus=2, orderType=1, userID=11}
2018-11:24 23:41:27.656 [Timer-0] [INFO] [c.h.server.service.HeartBeatService] - DeviceConnect disconnect 898604301118C1638029
2018-11:24 23:41:27.660 [Timer-0] [INFO] [com.hansun.server.db.DataStore] - update device before 1 update value device{id=75deviceID=201808020030, type=100, name=null, locationID=20, userID=11, status=0, simCard=898604301118C1638029, port=1, managerStatus=0, consumeType=4, version=01, storeID=1}
2018-11:24 23:41:27.661 [Timer-0] [INFO] [c.h.server.service.HeartBeatService] - DeviceConnect disconnect 898604301118C1638018
2018-11:24 23:41:27.664 [Timer-0] [INFO] [com.hansun.server.db.DataStore] - update device before 1 update value device{id=64deviceID=201808020019, type=100, name=null, locationID=20, userID=11, status=0, simCard=898604301118C1638018, port=1, managerStatus=0, consumeType=4, version=01, storeID=1}
2018-11:24 23:41:31.742 [https-openssl-nio-443-exec-5] [INFO] [c.h.server.controller.DemoController] - paysuccess  userId = oKVP-1eTcEPEVXctxf1A38EqQigQ orderId = 2018112423404722974 device_id = 201808020007 product_id = 27
2018-11:24 23:41:31.742 [https-openssl-nio-443-exec-5] [ERROR] [c.hansun.server.service.OrderService] - can not create order for handler for device not exist  null
2018-11:24 23:41:31.743 [https-openssl-nio-443-exec-5] [ERROR] [c.hansun.server.service.OrderService] - createStartMsgToDevice error
com.hansun.server.common.ServerException: can not create order for handler for device not exist  null
	at com.hansun.server.service.OrderService.createStartMsgToDevice(OrderService.java:143)
	at com.hansun.server.service.OrderService$$FastClassBySpringCGLIB$$b057cdc1.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:651)
	at com.hansun.server.service.OrderService$$EnhancerBySpringCGLIB$$aae46683.createStartMsgToDevice(<generated>)
	at com.hansun.server.controller.DemoController.paysuccess(DemoController.java:543)
	at sun.reflect.GeneratedMethodAccessor249.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:114)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at com.hansun.server.filter.JwtAuthenticationTokenFilter.doFilterInternal(JwtAuthenticationTokenFilter.java:71)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:87)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by yuanl2** [comment]
2018-11:24 23:40:47.654 [Timer-0] [INFO] [c.h.server.commu.SocketHandler4G] - handleClose 898604301118C1638006
2018-11:24 23:40:47.661 [Timer-0] [ERROR] [com.hansun.server.commu.LinkManger] - LinkManger not contains deviceSimCard = 898604301118C1638006

**Comment by yuanl2** [comment]
2018-11:24 23:40:47.654 [Timer-0] [INFO] [c.h.server.commu.SocketHandler4G] - handleClose 898604301118C1638006


2018-11:24 23:40:47.333 [https-openssl-nio-443-exec-6] [INFO] [c.h.s.controller.WXPayController] - packge sign value:8BD3966D8D5FF93E98C254D8A31DB9F6
2018-11:24 23:40:47.339 [https-openssl-nio-443-exec-6] [INFO] [c.h.s.controller.WXPayController] - create order order{id=4201, orderID=2018112423404722974, deviceID=201808020007, deviceName=null, consumeType=27, startTime=null, endTime=null, duration=910, price=10.0, createTime=2018-11-24T23:40:47.334, orderStatus=0, orderType=1, userID=11}
2018-11:24 23:40:47.654 [Timer-0] [INFO] [c.h.server.service.HeartBeatService] - DeviceConnect disconnect 898604301118C1638006
2018-11:24 23:40:47.661 [Timer-0] [INFO] [com.hansun.server.db.DataStore] - update device before 1 update value device{id=52deviceID=201808020007, type=100, name=null, locationID=20, userID=11, status=0, simCard=898604301118C1638006, port=1, managerStatus=0, consumeType=4, version=01, storeID=1}
2018-11:24 23:40:53.345 [https-openssl-nio-443-exec-10] [INFO] [c.h.s.controller.WXPayController] - wechat pay callback : modify order = 2018112423404722974 status to PAYDONE 
2018-11:24 23:40:53.350 [https-openssl-nio-443-exec-10] [INFO] [com.hansun.server.db.OrderStore] - update order = order{id=4201, orderID=2018112423404722974, deviceID=201808020007, deviceName=null, consumeType=27, startTime=null, endTime=null, duration=910, price=10.0, createTime=2018-11-24T23:40:47, orderStatus=2, orderType=1, userID=11}
2018-11:24 23:41:27.656 [Timer-0] [INFO] [c.h.server.service.HeartBeatService] - DeviceConnect disconnect 898604301118C1638029
2018-11:24 23:41:27.660 [Timer-0] [INFO] [com.hansun.server.db.DataStore] - update device before 1 update value device{id=75deviceID=201808020030, type=100, name=null, locationID=20, userID=11, status=0, simCard=898604301118C1638029, port=1, managerStatus=0, consumeType=4, version=01, storeID=1}
2018-11:24 23:41:27.661 [Timer-0] [INFO] [c.h.server.service.HeartBeatService] - DeviceConnect disconnect 898604301118C1638018
2018-11:24 23:41:27.664 [Timer-0] [INFO] [com.hansun.server.db.DataStore] - update device before 1 update value device{id=64deviceID=201808020019, type=100, name=null, locationID=20, userID=11, status=0, simCard=898604301118C1638018, port=1, managerStatus=0, consumeType=4, version=01, storeID=1}
2018-11:24 23:41:31.742 [https-openssl-nio-443-exec-5] [INFO] [c.h.server.controller.DemoController] - paysuccess  userId = oKVP-1eTcEPEVXctxf1A38EqQigQ orderId = 2018112423404722974 device_id = 201808020007 product_id = 27
2018-11:24 23:41:31.742 [https-openssl-nio-443-exec-5] [ERROR] [c.hansun.server.service.OrderService] - can not create order for handler for device not exist  null
2018-11:24 23:41:31.743 [https-openssl-nio-443-exec-5] [ERROR] [c.hansun.server.service.OrderService] - createStartMsgToDevice error

用户在点击创建订单之前，设备状态还是正常，但是在支付之后，设备断链了。所以这个时候下发设备消息是失败的。

后面针对此种情况，下发设备消息之前判断设备的状态，如果断链。直接返回异常并退款
